spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

s3:
  bucket: ${S3_BUCKET}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}

social:
  google:
    baseUrl: https://accounts.google.com
    apiBaseUrl: https://www.googleapis.com
    clientId: ${GOOGLE_CLIENT_ID}
    redirectUri: ${GOOGLE_REDIRECT_URI}
    secretKey: ${GOOGLE_SECRET_KEY}
    scope: email profile

app:
  cors:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
  logging:
    exception:
      structured-enabled: true
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl: P30D
    refresh-token-ttl: P30D
